// AddEmployeeScreen.java
// This screen lets HR Admin add a new employee to the database.
// The empID is auto-generated by MySQL so HR Admin does not enter it.

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

public class AddEmployeeScreen extends JFrame {

    private JTextField fnameField, lnameField, emailField, hireDateField;
    private JTextField salaryField, ssnField, streetField, cityField;
    private JTextField stateField, zipField, dobField, phoneField;
    private JTextField emergencyNameField, emergencyPhoneField;
    private JLabel messageLabel;

    public AddEmployeeScreen() {
        setTitle("Add New Employee");
        setSize(500, 680);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);

        JPanel panel = new JPanel(new GridBagLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(15, 30, 15, 30));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Title
        JLabel title = new JLabel("Add New Employee", SwingConstants.CENTER);
        title.setFont(new Font("Arial", Font.BOLD, 16));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        panel.add(title, gbc);
        gbc.gridwidth = 1;

        int row = 1;

        // First Name
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("First Name:"), gbc);
        fnameField = new JTextField(20); gbc.gridx = 1; panel.add(fnameField, gbc); row++;

        // Last Name
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Last Name:"), gbc);
        lnameField = new JTextField(20); gbc.gridx = 1; panel.add(lnameField, gbc); row++;

        // Email
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Email:"), gbc);
        emailField = new JTextField(20); gbc.gridx = 1; panel.add(emailField, gbc); row++;

        // Hire Date - format MM-DD-YYYY
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Hire Date (MM-DD-YYYY):"), gbc);
        hireDateField = new JTextField(20); gbc.gridx = 1; panel.add(hireDateField, gbc); row++;

        // Salary
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Salary:"), gbc);
        salaryField = new JTextField(20); gbc.gridx = 1; panel.add(salaryField, gbc); row++;

        // SSN
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("SSN (used as password):"), gbc);
        ssnField = new JTextField(20); gbc.gridx = 1; panel.add(ssnField, gbc); row++;

        // Address section
        JLabel addrTitle = new JLabel("-- Address & Contact Info --", SwingConstants.CENTER);
        addrTitle.setFont(new Font("Arial", Font.BOLD, 12));
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; panel.add(addrTitle, gbc);
        gbc.gridwidth = 1; row++;

        // Street
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Street:"), gbc);
        streetField = new JTextField(20); gbc.gridx = 1; panel.add(streetField, gbc); row++;

        // City
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("City:"), gbc);
        cityField = new JTextField(20); gbc.gridx = 1; panel.add(cityField, gbc); row++;

        // State
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("State (e.g. GA):"), gbc);
        stateField = new JTextField(20); gbc.gridx = 1; panel.add(stateField, gbc); row++;

        // Zip
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Zip Code:"), gbc);
        zipField = new JTextField(20); gbc.gridx = 1; panel.add(zipField, gbc); row++;

        // Date of Birth - format MM-DD-YYYY
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Date of Birth (MM-DD-YYYY):"), gbc);
        dobField = new JTextField(20); gbc.gridx = 1; panel.add(dobField, gbc); row++;

        // Phone - 10 digits only
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Phone (10 digits):"), gbc);
        phoneField = new JTextField(20); gbc.gridx = 1; panel.add(phoneField, gbc); row++;

        // Emergency Contact Name
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Emergency Contact Name:"), gbc);
        emergencyNameField = new JTextField(20); gbc.gridx = 1; panel.add(emergencyNameField, gbc); row++;

        // Emergency Contact Phone - 10 digits only
        gbc.gridx = 0; gbc.gridy = row; panel.add(new JLabel("Emergency Contact Phone (10 digits):"), gbc);
        emergencyPhoneField = new JTextField(20); gbc.gridx = 1; panel.add(emergencyPhoneField, gbc); row++;

        // Save button
        JButton saveBtn = new JButton("Save Employee");
        saveBtn.setFont(new Font("Arial", Font.BOLD, 13));
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; panel.add(saveBtn, gbc); row++;

        // Cancel button
        JButton cancelBtn = new JButton("Cancel");
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; panel.add(cancelBtn, gbc); row++;

        // Message label
        messageLabel = new JLabel("", SwingConstants.CENTER);
        messageLabel.setForeground(Color.RED);
        gbc.gridx = 0; gbc.gridy = row; gbc.gridwidth = 2; panel.add(messageLabel, gbc);

        JScrollPane scrollPane = new JScrollPane(panel);
        add(scrollPane);

        saveBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) { saveEmployee(); }
        });

        cancelBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) { dispose(); }
        });

        setVisible(true);
    }

    // converts MM-DD-YYYY to YYYY-MM-DD for MySQL
    private String convertDate(String input) {
        // expects MM-DD-YYYY
        if (input == null || input.trim().isEmpty()) return null;
        String[] parts = input.trim().split("-");
        if (parts.length != 3) return null;
        // return as YYYY-MM-DD
        return parts[2] + "-" + parts[0] + "-" + parts[1];
    }

    // validates phone is exactly 10 digits
    private boolean isValidPhone(String phone) {
        if (phone == null || phone.trim().isEmpty()) return true; // optional field
        String digitsOnly = phone.trim().replaceAll("[^0-9]", "");
        return digitsOnly.length() == 10;
    }

    // formats phone to store as digits only
    private String formatPhone(String phone) {
        if (phone == null || phone.trim().isEmpty()) return "";
        return phone.trim().replaceAll("[^0-9]", "");
    }

    private void saveEmployee() {
        String fname      = fnameField.getText().trim();
        String lname      = lnameField.getText().trim();
        String email      = emailField.getText().trim();
        String hireDate   = hireDateField.getText().trim();
        String salaryText = salaryField.getText().trim();
        String ssn        = ssnField.getText().trim();
        String street     = streetField.getText().trim();
        String city       = cityField.getText().trim();
        String state      = stateField.getText().trim();
        String zip        = zipField.getText().trim();
        String dob        = dobField.getText().trim();
        String phone      = phoneField.getText().trim();
        String emergName  = emergencyNameField.getText().trim();
        String emergPhone = emergencyPhoneField.getText().trim();

        // check required fields
        if (fname.isEmpty() || lname.isEmpty() || email.isEmpty() ||
            hireDate.isEmpty() || salaryText.isEmpty() || ssn.isEmpty() ||
            street.isEmpty() || city.isEmpty() || state.isEmpty() || zip.isEmpty()) {
            messageLabel.setForeground(Color.RED);
            messageLabel.setText("Please fill in all required fields.");
            return;
        }

        // validate salary
        double salary;
        try {
            salary = Double.parseDouble(salaryText);
        } catch (NumberFormatException e) {
            messageLabel.setForeground(Color.RED);
            messageLabel.setText("Salary must be a number.");
            return;
        }

        // validate state
        if (state.length() != 2) {
            messageLabel.setForeground(Color.RED);
            messageLabel.setText("State must be 2 letters (e.g. GA).");
            return;
        }

        // validate hire date format MM-DD-YYYY
        String hireDateSQL = convertDate(hireDate);
        if (hireDateSQL == null) {
            messageLabel.setForeground(Color.RED);
            messageLabel.setText("Hire date must be MM-DD-YYYY format. Example: 04-20-2026");
            return;
        }

        // validate date of birth format MM-DD-YYYY (optional)
        String dobSQL = null;
        if (!dob.isEmpty()) {
            dobSQL = convertDate(dob);
            if (dobSQL == null) {
                messageLabel.setForeground(Color.RED);
                messageLabel.setText("Date of birth must be MM-DD-YYYY format. Example: 01-15-1990");
                return;
            }
        }

        // validate phone numbers are 10 digits
        if (!phone.isEmpty() && !isValidPhone(phone)) {
            messageLabel.setForeground(Color.RED);
            messageLabel.setText("Phone must be exactly 10 digits.");
            return;
        }

        if (!emergPhone.isEmpty() && !isValidPhone(emergPhone)) {
            messageLabel.setForeground(Color.RED);
            messageLabel.setText("Emergency phone must be exactly 10 digits.");
            return;
        }

        try {
            Connection conn = DatabaseConnection.getConnection();

            int cityID  = getOrCreateCity(conn, city);
            int stateID = getStateID(conn, state.toUpperCase());

            if (stateID == -1) {
                messageLabel.setForeground(Color.RED);
                messageLabel.setText("State not found. Use 2 letter code like GA.");
                conn.close();
                return;
            }

            // insert employee
            String empQuery = "INSERT INTO employees (Fname, Lname, email, HireDate, Salary, SSN) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement empStmt = conn.prepareStatement(empQuery, Statement.RETURN_GENERATED_KEYS);
            empStmt.setString(1, fname);
            empStmt.setString(2, lname);
            empStmt.setString(3, email);
            empStmt.setString(4, hireDateSQL);
            empStmt.setDouble(5, salary);
            empStmt.setString(6, ssn);
            empStmt.executeUpdate();

            // get auto generated empID
            ResultSet keys = empStmt.getGeneratedKeys();
            int newEmpID = -1;
            if (keys.next()) { newEmpID = keys.getInt(1); }

            // insert address
            String addrQuery = "INSERT INTO addresses (empid, street, cityID, stateID, zip, DOB, phone, emergency_contact, emergency_phone) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement addrStmt = conn.prepareStatement(addrQuery);
            addrStmt.setInt(1, newEmpID);
            addrStmt.setString(2, street);
            addrStmt.setInt(3, cityID);
            addrStmt.setInt(4, stateID);
            addrStmt.setString(5, zip);
            addrStmt.setString(6, dobSQL);
            addrStmt.setString(7, formatPhone(phone));
            addrStmt.setString(8, emergName);
            addrStmt.setString(9, formatPhone(emergPhone));
            addrStmt.executeUpdate();

            conn.close();

            messageLabel.setForeground(new Color(0, 150, 0));
            messageLabel.setText("Employee added! New empID = " + newEmpID);
            clearFields();

        } catch (SQLException ex) {
            messageLabel.setForeground(Color.RED);
            messageLabel.setText("Error: " + ex.getMessage());
        }
    }

    private int getOrCreateCity(Connection conn, String cityName) throws SQLException {
        PreparedStatement stmt = conn.prepareStatement("SELECT cityID FROM cities WHERE cityName = ?");
        stmt.setString(1, cityName);
        ResultSet rs = stmt.executeQuery();
        if (rs.next()) return rs.getInt("cityID");
        PreparedStatement ins = conn.prepareStatement("INSERT INTO cities (cityName) VALUES (?)", Statement.RETURN_GENERATED_KEYS);
        ins.setString(1, cityName);
        ins.executeUpdate();
        ResultSet k = ins.getGeneratedKeys();
        k.next();
        return k.getInt(1);
    }

    private int getStateID(Connection conn, String stateAbbr) throws SQLException {
        PreparedStatement stmt = conn.prepareStatement("SELECT stateID FROM states WHERE stateAbbr = ?");
        stmt.setString(1, stateAbbr);
        ResultSet rs = stmt.executeQuery();
        if (rs.next()) return rs.getInt("stateID");
        return -1;
    }

    private void clearFields() {
        fnameField.setText(""); lnameField.setText(""); emailField.setText("");
        hireDateField.setText(""); salaryField.setText(""); ssnField.setText("");
        streetField.setText(""); cityField.setText(""); stateField.setText("");
        zipField.setText(""); dobField.setText(""); phoneField.setText("");
        emergencyNameField.setText(""); emergencyPhoneField.setText("");
    }
}
